env:
  es6: true
  node: true
  mocha: true
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: 2022
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
extends:
  - plugin:@typescript-eslint/recommended
  - prettier
rules:
  prettier/prettier:
    - error
    # "@typescript-eslint/no-explicit-any": 'off'
    # "@typescript-eslint/no-empty-interface": 'off'
