variables:
  - &node_image 'node:20-alpine'

pipeline:
  lint-markdown:
    image: markdownlint/markdownlint:latest
    group: test
    commands:
      - mdl .

  check-pre-commit:
    image: python:latest
    group: test
    environment:
      - SKIP=no-commit-to-branch # Ignore "don't commit to protected branch" check
    commands:
      - pip install pre-commit
      - pre-commit run --all-files

  node-install-dependencies:
    image: *node_image
    commands:
      - npm clean-install

  node-lint:
    image: *node_image
    group: test
    commands:
      - npm run lint

  node-format:
    image: *node_image
    group: test
    commands:
      - npm run format

  node-test:
    image: *node_image
    commands:
      - echo '{"user_id":"ci-dummy","access_token":"ci-dummy","home_server":"ci-dummy","device_id":"ci-dummy"}' > src/config/synapse_access_token.json
      - npm test

  node-compile:
    image: *node_image
    commands:
      - echo '{"user_id":"ci-dummy","access_token":"ci-dummy","home_server":"ci-dummy","device_id":"ci-dummy"}' > src/config/synapse_access_token.json
      - npm run compile
