when:
  - event: [tag, push]

variables:
  - &node_image 'node:22-alpine@sha256:ba898e86c2cc720c8cf2ae05f8d2d4697fe0c8ca3e920d6fbf14a6cbf50bb9ca'

services:
  synapse:
    image: docker.io/matrixdotorg/synapse:v1.110.0@sha256:d59f1365bf154d0ebd06d35511e44e38d62d221fa771775891d962a29caf7e13
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_SERVER_NAME=synapse
      - SYNAPSE_REPORT_STATS=no
    ports:
      - 8008
    volumes:
      - /mnt/synapse:/data
    commands:
      - rm -rf /data/*
      - /start.py generate
      - sed -ri '/^registration_shared_secret:.*$/d' /data/homeserver.yaml
      - echo >> /data/homeserver.yaml
      - cat test/homeserver_additions.yaml >> /data/homeserver.yaml
      - cp app-service.example.yaml /data/app-service.yaml
      - chmod +r /data/*.signing.key
      - /start.py

steps:
  check-pre-commit:
    image: git.verdigado.com/verdigado-images/container-pre-commit:latest@sha256:f914d98ff40f94f9d4b1eee4542c2e6ca5929afe42fdf5a66fc17e9bf82f95cf
    environment:
      - SKIP=no-commit-to-branch # Ignore "don't commit to protected branch" check
    commands:
      - pre-commit run --all-files

  synapse-register-admin:
    image: docker.io/matrixdotorg/synapse:v1.110.0@sha256:d59f1365bf154d0ebd06d35511e44e38d62d221fa771775891d962a29caf7e13
    commands:
      - timeout 120 sh -c 'while !(( register_new_matrix_user http://synapse:8008 --shared-secret testrun --admin --user admin --password admin 2> /dev/null )); do sleep 1; done;'
      - 'curl --request POST --url http://synapse:8008/_matrix/client/v3/login --header "Content-Type: application/json" --data "{\"type\": \"m.login.password\",\"user\": \"admin\",\"password\": \"admin\",\"device_id\": \"DEV\"}" | tee src/config/synapse_access_token.json'

  node-install-dependencies:
    image: *node_image
    commands:
      - npm clean-install
    depends_on: [check-pre-commit]

  node-lint:
    image: *node_image
    commands:
      - npm run lint
    depends_on: [node-install-dependencies]

  node-test-units:
    image: *node_image
    commands:
      - npm test -- --ci --coverage --rootDir src/
    depends_on: [node-install-dependencies]

  node-test-e2e:
    image: *node_image
    environment:
      - REGISTRATION_SHARED_SECRET=testrun
      - AS_TOKEN=30c05ae90a248a4188e620216fa72e349803310ec83e2a77b34fe90be6081f46
      - SYNAPSE_URL=http://synapse:8008
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    commands:
      - apk add --update --no-cache sqlite
      - mkdir -p inputs
      - npx node-jq --compact-output '.' test/messages.json > inputs/rocketchat_message.json
      - npx node-jq --compact-output '.' test/rooms.json > inputs/rocketchat_room.json
      - npx node-jq --compact-output '.' test/users.json > inputs/users.json
      - npm start
      - sqlite3 db.sqlite .dump > db-snapshot.sql
      - npm test -- --ci --rootDir test/
      - npm start
      - npm test -- --ci --rootDir test/
      - diff db-snapshot.sql <(sqlite3 db.sqlite .dump)

    depends_on: [node-install-dependencies, synapse-register-admin]
