variables:
  - &node_image 'node:20.12.2-alpine@sha256:ec0c413b1d84f3f7f67ec986ba885930c57b5318d2eb3abc6960ee05d4f2eb28'

services:
  synapse:
    image: docker.io/matrixdotorg/synapse:v1.105.0@sha256:cbd56af58232394066d3ab9e55316ac92ed4b8b9392a829812e333f5178be6c0
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_SERVER_NAME=synapse
      - SYNAPSE_REPORT_STATS=no
    ports:
      - 8008
    volumes:
      - /mnt/synapse:/data
    commands:
      - rm -rf /data/*
      - /start.py generate
      - sed -ri '/^registration_shared_secret:.*$/d' /data/homeserver.yaml
      - echo >> /data/homeserver.yaml
      - cat test/homeserver_additions.yaml >> /data/homeserver.yaml
      - cp app-service.example.yaml /data/app-service.yaml
      - chmod +r /data/*.signing.key
      - /start.py

steps:
  check-pre-commit:
    image: git.verdigado.com/verdigado-images/container-pre-commit:latest@sha256:7fed51a85daa4826df5b4dc66fff439af8403fa2d9b2671f201a40ed0647f1e9
    environment:
      - SKIP=no-commit-to-branch # Ignore "don't commit to protected branch" check
    commands:
      - pre-commit run --all-files

  synapse-register-admin:
    image: docker.io/matrixdotorg/synapse:v1.105.0@sha256:cbd56af58232394066d3ab9e55316ac92ed4b8b9392a829812e333f5178be6c0
    commands:
      - timeout 120 sh -c 'while !(( register_new_matrix_user http://synapse:8008 --shared-secret testrun --admin --user admin --password admin 2> /dev/null )); do sleep 1; done;'
      - 'curl --request POST --url http://synapse:8008/_matrix/client/v3/login --header "Content-Type: application/json" --data "{\"type\": \"m.login.password\",\"user\": \"admin\",\"password\": \"admin\",\"device_id\": \"DEV\"}" | tee src/config/synapse_access_token.json'

  node-install-dependencies:
    image: *node_image
    commands:
      - npm clean-install
    depends_on: [check-pre-commit]

  node-lint:
    image: *node_image
    commands:
      - npm run lint
    depends_on: [node-install-dependencies]

  node-test-e2e:
    image: *node_image
    environment:
      - REGISTRATION_SHARED_SECRET=testrun
      - AS_TOKEN=30c05ae90a248a4188e620216fa72e349803310ec83e2a77b34fe90be6081f46
      - SYNAPSE_URL=http://synapse:8008
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    commands:
      - mkdir -p inputs
      - npx node-jq --compact-output '.' test/messages.json > inputs/rocketchat_message.json
      - npx node-jq --compact-output '.' test/rooms.json > inputs/rocketchat_room.json
      - npx node-jq --compact-output '.' test/users.json > inputs/users.json
      - npm start
    depends_on: [node-install-dependencies, synapse-register-admin]

  node-test-units:
    image: *node_image
    commands:
      - npm test --ci
    depends_on: [node-install-dependencies]

  node-compile:
    image: *node_image
    commands:
      - npm run compile
    depends_on: [node-install-dependencies]
